[build]
  # Directory with the build command
  base = "."
  
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  
  # Build command
  command = "npm ci && npm run build"

[[redirects]]
  # Handle client-side routing for React SPA
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Node.js version
  NODE_VERSION = "18"